apiVersion: apps/v1
kind: Deployment
metadata:
  name: capvision
  labels:
    app: capvision
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capvision
  template:
    metadata:
      labels:
        app: capvision
    spec:
      containers:
      - name: capvision
        image: mvrkrishna/capvision
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30000000
